# Docs: <https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-dependency-updates>

version: 2

updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "modem7"

  - package-ecosystem: github-actions
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "modem7"

  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "modem7"
