---

kind: pipeline
type: docker
name: latest

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfile
  image: hadolint/hadolint:latest-alpine
  pull: if-not-exists
  commands:
    - hadolint --version
    - hadolint ErrorPages/Dockerfile*

- name: latest  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/traefik-error-pages
    compress: true
    purge: true
    cache_from: "modem7/traefik-error-pages:latest"
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64/v8
      - linux/ppc64le
      - linux/s390x
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest
      - 1.2.1

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

# trigger:
  # event:
    # - cron
  # cron:
    # - errorpages_latest

trigger:
  event:
    - custom