kind: pipeline
type: docker
name: deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: deploy
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      repo: modem7/traefik-error-pages
      # dry_run: true  # disable when not testing
      purge: true
      compress: true
      use_cache: true
      cache_from: "modem7/traefik-error-pages:latest"
      platforms:  # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v7
      - linux/arm64/v8
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - 2.2.0

  - name: slack
    image: themaz/drone-slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status: [ success, failure ]

trigger:
  event:
    - custom
