name: demo

on:
  workflow_dispatch:

jobs:
  demo:
    name: Update the demonstration
    runs-on: ubuntu-20.04
    steps:
      - name: DroneCI Build Trigger
        # You may pin to the exact commit or the version.
        # uses: kzonix/drone-ci-trigger@03d7df83e955a100e8a721cfe39de9b980822f1e
        uses: kzonix/drone-ci-trigger@0.0.2
        with:
          # URL of API for interacting with the Drone server. Example: http://localhost:8080/api
          droneApiUrl: 'http://drone.modem7.com/api'
          # Drone API Personal Token
          droneApiToken: '$DRONE_TOKEN'
          
      - uses: gacts/github-slug@v1
        id: slug

      - name: Take rendered templates from the built docker image
        run: |
          docker create --name img modem7/traefik-error-pages:latest
          docker cp img:/opt/html ./out
          docker rm -f img

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
